name: Auto-Update Module Index

on:
  push:
    paths:
      - 'lune/module_descriptions.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate MODULE_INDEX.md
        run: |
          python3 -c "
import json
with open('lune/module_descriptions.json') as f:
    mods = json.load(f)
with open('MODULE_INDEX.md', 'w') as f:
    f.write('# 🧩 Module Index\n\n| Module | Description |\n|--------|-------------|\n')
    for mod, desc in sorted(mods.items()):
        f.write(f'| `{mod}` | {desc} |\n')
"

      - name: Commit & Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add MODULE_INDEX.md
          git diff --cached --quiet || git commit -m 'Auto-update MODULE_INDEX.md from GitHub Action'
          git push
